# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - vsinsertions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Remove the 'deploy: staging' label from other PRs.
      - uses: actions/checkout@v4
      - name: Remove label
        uses: actions/github-script@v7
        env:
          WORKSPACE_DIR: ${{ github.workspace }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workspacePath = process.env.WORKSPACE_DIR.replaceAll('\\', '/');
            const { default: removeLabel } = await import(`file://${workspacePath}/eng/remove-label.mjs`);
            await removeLabel();
