name: Staging Deploy

on:
  workflow_dispatch:
  pull_request:
    # Note: we don't trigger on "labeled" because multiple labels would trigger duplicate builds.
    # Instead you can push new commits or close and re-open the PR to trigger a staging deployment.
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

  deploy:
    if: ${{ contains(github.event.pull_request.labels.*.name, format('deploy{0} staging', ':')) || github.event_name == 'workflow_dispatch' }}

    runs-on: windows-latest
    needs: build
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v5
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vsinsertions-staging'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_Staging }}
          package: .

      # Remove the 'deploy: staging' label from other PRs.
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'workflow_dispatch' }}
      - name: Remove label
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/github-script@v7
        env:
          WORKSPACE_DIR: ${{ github.workspace }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workspacePath = process.env.WORKSPACE_DIR.replaceAll('\\', '/');
            const { default: removeLabel } = await import(`file://${workspacePath}/eng/remove-label.mjs`);
            await removeLabel({ context, github });
